[tool.poetry]
name = "wakabox"
version = "0.1.0"
description = ""
authors = ["wavy-cat <52543076+wavy-cat@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
